import smtplib
import random
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from core.models import SMTPSettings

def generate_otp():
    """Generates a secure 6-digit OTP"""
    return str(random.randint(100000, 999999))

def send_otp_email(to_email, company_name, otp):
    """Sends the OTP using the database SMTP configuration"""
    settings = SMTPSettings.query.first()
    
    if not settings:
        return False, "SMTP settings are not configured by the SuperAdmin."

    try:
        msg = MIMEMultipart()
        msg['From'] = settings.sender_email
        msg['To'] = to_email
        msg['Subject'] = "Security Alert: Password Reset OTP"

        # Premium HTML Email formatting
        body = f"""
        <html>
            <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
                <h2 style="color: #66796B;">Workspace Security</h2>
                <p>Hello <strong>{company_name}</strong>,</p>
                <p>We received a request to change the password for your workspace.</p>
                <div style="background-color: #F8F5F1; padding: 15px; border-radius: 8px; margin: 20px 0; display: inline-block; border: 1px solid #D4C2AD;">
                    <p style="margin: 0; font-size: 14px; color: #BA8E7A; text-transform: uppercase; font-weight: bold;">Your OTP Code:</p>
                    <h1 style="margin: 5px 0 0 0; color: #2C3530; letter-spacing: 5px;">{otp}</h1>
                </div>
                <p>This code will expire in <strong>10 minutes</strong>.</p>
                <p>If you did not request this change, please ignore this email.</p>
                <br>
                <p style="font-size: 12px; color: #999;">Securely generated by Enterprise SaaS Billing.</p>
            </body>
        </html>
        """
        
        msg.attach(MIMEText(body, 'html'))

        # Connect to the SMTP Server
        server = smtplib.SMTP(settings.server, settings.port)
        if settings.use_tls:
            server.starttls()
            
        server.login(settings.username, settings.password)
        server.send_message(msg)
        server.quit()
        
        return True, "OTP sent successfully!"
    except Exception as e:
        return False, str(e)