import smtplib
import random
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from core.models import SMTPSettings

def generate_otp():
    """Generates a secure 6-digit OTP"""
    return str(random.randint(100000, 999999))

def send_otp_email(to_email, company_name, otp):
    """Sends the OTP using the database SMTP configuration"""
    settings = SMTPSettings.query.first()
    
    if not settings:
        return False, "SMTP settings are not configured by the SuperAdmin."

    try:
        msg = MIMEMultipart()
        msg['From'] = settings.sender_email
        msg['To'] = to_email
        msg['Subject'] = "Security Alert: Password Reset OTP"

        # Premium HTML Email formatting
        body = f"""
        <html>
            <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
                <h2 style="color: #66796B;">Workspace Security</h2>
                <p>Hello <strong>{company_name}</strong>,</p>
                <p>We received a request to change the password for your workspace.</p>
                <div style="background-color: #F8F5F1; padding: 15px; border-radius: 8px; margin: 20px 0; display: inline-block; border: 1px solid #D4C2AD;">
                    <p style="margin: 0; font-size: 14px; color: #BA8E7A; text-transform: uppercase; font-weight: bold;">Your OTP Code:</p>
                    <h1 style="margin: 5px 0 0 0; color: #2C3530; letter-spacing: 5px;">{otp}</h1>
                </div>
                <p>This code will expire in <strong>10 minutes</strong>.</p>
                <p>If you did not request this change, please ignore this email.</p>
                <br>
                <p style="font-size: 12px; color: #999;">Securely generated by Enterprise SaaS Billing.</p>
            </body>
        </html>
        """
        
        msg.attach(MIMEText(body, 'html'))

        # Connect to the SMTP Server
        server = smtplib.SMTP(settings.server, settings.port)
        if settings.use_tls:
            server.starttls()
            
        server.login(settings.username, settings.password)
        server.send_message(msg)
        server.quit()
        
        return True, "OTP sent successfully!"
    except Exception as e:
        return False, str(e)
    
   #whatsapp automation to remove it just remove below code 
import requests
import json

def send_greenapi_whatsapp(phone_number, customer_name, company_name, invoice_no, amount, invoice_link):
    """
    Sends an automated WhatsApp message using Green API.
    """
    # ⚠️ Replace these with your actual credentials from the Green API Console
    ID_INSTANCE = "7107590992"
    API_TOKEN_INSTANCE = "8946294447a54c5cbb5d402068342d165bc1b9f76ac44e129f"
    
    url = f"https://api.green-api.com/waInstance{ID_INSTANCE}/sendMessage/{API_TOKEN_INSTANCE}"
    
    # 1. Format the phone number (Green API requires CountryCode + Number + @c.us)
    clean_phone = phone_number.replace("+", "").replace(" ", "").replace("-", "")
    if len(clean_phone) == 10:
        clean_phone = "91" + clean_phone  # Add 91 if it's a 10-digit Indian number
        
    chat_id = f"{clean_phone}@c.us" # 🎯 THIS IS CRUCIAL FOR GREEN API
    
    # 2. Construct the exact message body
    message_body = (
        f"Hello {customer_name},\n\n"
        f"This is an automated message from *{company_name}*.\n"
        f"Your invoice *{invoice_no}* for the total amount of *₹{amount}* has been generated.\n\n"
        f"📄 *Click the secure link below to view and download your PDF Invoice:*\n"
        f"{invoice_link}\n\n"
        f"Thank you for your business!"
    )
    
    payload = {
        "chatId": chat_id,
        "message": message_body
    }
    
    headers = {
        'Content-Type': 'application/json'
    }
    
    try:
        response = requests.post(url, headers=headers, data=json.dumps(payload))
        if response.status_code == 200:
            return True, "WhatsApp sent successfully via Green API!"
        else:
            print(f"Green API Error: {response.text}")
            return False, f"Green API Error: {response.text}"
    except Exception as e:
        print(f"Exception: {e}")
        return False, str(e)